### GET ALL
GET http://localhost:3000/api/sondas HTTP/1.1

### GET BY ID
GET http://localhost:3000/api/sondas/<ID> HTTP/1.1

### CREATE sondas
POST http://localhost:3000/api/sondas HTTP/1.1
Content-Type: application/json

{
  "sondaName": "B2",
  "description": "sonda funcional",
  "location": "Valencia"
}

### UPDATE sondas
PUT http://localhost:3000/api/sondas/690de89592fa18aff7064f38 HTTP/1.1
Content-Type: application/json

{
  "sondaName": "C3",
  "description": "funciona",
  "location": "Cordoba"
}

### DELETE sondas
DELETE http://localhost:3000/api/sondas/<ID> HTTP/1.1
