### GET ALL
GET http://localhost:3000/api/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTYzY2IyOTY4YTEwOTQzOGQ5Y2JiZWEiLCJpYXQiOjE3NjgxNDgyNjIsImV4cCI6MTc2ODE1NTQ2Mn0.8gaO65392EjNmFyMjAXqZHTvDd647keEh4tZTOwADzk

### GET BY ID
GET http://localhost:3000/api/users/690de86f8fe7d64cc2c4037d HTTP/1.1

### REGISTER USER
POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "username": "Fernando",
  "fullName": "Fernando Gonzalez",
  "description": "test2",
  "email": "test@email.com",
  "password": "coolpassword1"
}

### LOGIN USER
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "coolpassword1"
}

### UPDATE USER
PUT http://localhost:3000/api/users/<ID> HTTP/1.1
Content-Type: application/json

{
  "username": "soph",
  "fullName": "Sofía Gilsanz",
  "description": "la descripcion ha cambiado",
  "email": "test@email.com",
  "password": "coolpassword"
}

### DELETE USER
DELETE http://localhost:3000/api/users/<ID> HTTP/1.1
