### GET ALL
GET https://localhost:3000/api/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTg3MjUwZWUwZmEzZTg3NzQ5MTU0MTIiLCJpYXQiOjE3NzA0NjQ1MjYsImV4cCI6MTc3MDQ3MTcyNn0.reXFXeQ6JodcmL0RyipIZ42LLPIv6n3xJQ-u2lfStlE

### GET BY ID
GET http://localhost:3000/api/users/690de86f8fe7d64cc2c4037d HTTP/1.1

### REGISTER USER
POST https://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "username": "Fernanda",
  "fullName": "Fernanda Gonzalez",
  "description": "test2",
  "email": "test2@email.com",
  "password": "coolpassword1"
}

### LOGIN USER
POST https://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "test2@email.com",
  "password": "coolpassword1"
}

### UPDATE USER
PUT https://localhost:3000/api/users/6963cb2968a109438d9cbbea HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTg3MjUwZWUwZmEzZTg3NzQ5MTU0MTIiLCJpYXQiOjE3NzA0NjQ1MjYsImV4cCI6MTc3MDQ3MTcyNn0.reXFXeQ6JodcmL0RyipIZ42LLPIv6n3xJQ-u2lfStlE
Content-Type: application/json

{
  "username": "soph",
  "fullName": "Sofía Gilsanz",
  "description": "la descripcion ha cambiado",
  "email": "test@email.com",
  "password": "coolpassword"
}

### DELETE USER
DELETE http://localhost:3000/api/users/6963f0b5154eddcd84bd1f2e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTYzZjBiNTE1NGVkZGNkODRiZDFmMmUiLCJpYXQiOjE3NjgxNTczNjUsImV4cCI6MTc2ODE2NDU2NX0.zLSFWtj5_mPoj1_b14ylUPGGFhYyHXCiZe5zrM-8aN8